# apisix-registry-agent 配置模板
admin_api: "http://apisix:9180/apisix/admin"
admin_key: "your-admin-key"
service_version: "v1.0.0"
service_name: "service-name"
service_id: "service-id"
service_port: 8082
proto_path: "../proto/service.proto"
proto_pb_path: "./proto/service.pb"
route_plugins:
  - name: "grpc-transcode"
    config:
      proto_id: "service-id"
      service: "auth.AuthService"
      deadline: 10
ttl: 60
max_retry: 5
retry_interval: 2s
upstream:
  type: roundrobin
  nodes:
    "zenglow-auth-service:8082": 1

